### ISSUE TITLE
Logging with async handlers

### ISSUE THREAD

**Issue by johnbrett** [devinivy/toys#2]
Hi Devin, awesome utility module first of all! 🥇 

What do you about the lack of logging with async handlers when using toys? The default behaviour at the moment is to return the typical `500` internal error response, but if you're watching the hapi logs you're none the wiser you're returning 500's when it comes to debugging or viewing logs.

This is not specific to `Toys.handler` btw, hapi hides these for promise errors also, I've been unable to find a one-size-fits all solution to this yet though. 

Gist with a test server to see the different cases: https://gist.github.com/johnbrett/79b4cd7a3b57c8f6c9574f407a1b4c7e

**Comment by devinivy** [comment]
Hey, thanks!  That's a good point.  I could imagine tying in logging as provided by hapi by its "protect"ion that it wraps handlers with: https://github.com/hapijs/hapi/blob/master/lib/protect.js

I'd like to try your examples with the latest hapi updates (https://github.com/hapijs/hapi/pull/3486) to see what belongs in hapi, what belongs in toys, and if toys needs to a fill any gaps until hapi catches-up.

**Comment by johnbrett** [comment]
Yeah I'd saw those changes landed, but still didn't fix the not-logging issues, or so I found with the attached gist. I was about to create this PR (https://github.com/johnbrett/toys/commit/896bebe0c46df870c6af98ba06e517e654dfd836) but realised that didn't solve all of the problems either, there's still some cases not covered. 

Anything I can do to tell help let me know, I'm semi-familiar with the hapi internals, I've looked at them enough times around the promise issues!

**Comment by devinivy** [comment]
Hey @johnbrett is this something you're hoping to move forward with?  Toys v2 is out supporting hapi v17, but I would still accept a PR to toys v1 supporting hapi v16.

**Comment by johnbrett** [comment]
Hi @devinivy, I'm assuming hapi v17 will solve this for me (I haven't gotten to play with it much yet :/) so will close this! Thanks for considering it, apologies I didn't get the chance to implement it!

**Comment by devinivy** [comment]
Hey, no problem!
